#!/usr/bin/python
# -*- coding: utf-8 -*-
#  Copyright (C) 2019 Sascha Montellese <montellese@kodi.tv>
#
#  SPDX-License-Identifier: GPL-2.0-or-later
#  See LICENSES/README.md for more information.
#
"""
Various constant variables used by the plex library.
"""

import xbmcmediaimport  # pylint: disable=import-error

# import related constants
SUPPORTED_MEDIA_TYPES = {
    xbmcmediaimport.MediaTypeMovie,
    xbmcmediaimport.MediaTypeVideoCollection,
    xbmcmediaimport.MediaTypeMusicVideo,
    xbmcmediaimport.MediaTypeTvShow,
    xbmcmediaimport.MediaTypeSeason,
    xbmcmediaimport.MediaTypeEpisode
}

# API related constants
REQUEST_TIMEOUT = 5

PLEX_PROTOCOL = 'plex'
PLEX_HEADER_TOKEN = 'X-Plex-Token'

WS_MESSAGE_NOTIFICATION_CONTAINER = 'NotificationContainer'
WS_MESSAGE_NOTIFICATION_TYPE = 'type'
WS_MESSAGE_NOTIFICATION_TYPE_TIMELINE = 'timeline'
WS_MESSAGE_NOTIFICATION_TYPE_PLAYING = 'playing'
WS_MESSAGE_NOTIFICATION_TYPE_ACTIVITY = 'activity'
# WS_MESSAGE_NOTIFICATION_TYPE_BACKGROUND_PROCESSING_QUEUE = 'backgroundProcessingQueue'
WS_MESSAGE_NOTIFICATION_SIZE = 'size'

WS_MESSAGE_NOTIFICATION_TIMELINE_ENTRY = 'TimelineEntry'
WS_MESSAGE_NOTIFICATION_TIMELINE_ENTRY_IDENTIFIER = 'identifier'
WS_MESSAGE_NOTIFICATION_TIMELINE_ENTRY_IDENTIFIER_LIBRARY = 'com.plexapp.plugins.library'
# WS_MESSAGE_NOTIFICATION_TIMELINE_ENTRY_SECTION_ID = 'sectionID'
WS_MESSAGE_NOTIFICATION_TIMELINE_ENTRY_ITEM_ID = 'itemID'
WS_MESSAGE_NOTIFICATION_TIMELINE_ENTRY_TYPE = 'type'
WS_MESSAGE_NOTIFICATION_TIMELINE_ENTRY_TYPE_MOVIE = 1
WS_MESSAGE_NOTIFICATION_TIMELINE_ENTRY_TYPE_TVSHOW = 2
WS_MESSAGE_NOTIFICATION_TIMELINE_ENTRY_TYPE_SEASON = 3
WS_MESSAGE_NOTIFICATION_TIMELINE_ENTRY_TYPE_EPISODE = 4
# WS_MESSAGE_NOTIFICATION_TIMELINE_ENTRY_TYPE_ARTIST = 8
# WS_MESSAGE_NOTIFICATION_TIMELINE_ENTRY_TYPE_ALBUM = 9
# WS_MESSAGE_NOTIFICATION_TIMELINE_ENTRY_TYPE_SONG = 10
# WS_MESSAGE_NOTIFICATION_TIMELINE_ENTRY_TYPE_EXTRAS = 12
# WS_MESSAGE_NOTIFICATION_TIMELINE_ENTRY_TYPE_PHOTO = 14
WS_MESSAGE_NOTIFICATION_TIMELINE_ENTRY_STATE = 'state'
WS_MESSAGE_NOTIFICATION_TIMELINE_ENTRY_STATE_CREATED = 0
# WS_MESSAGE_NOTIFICATION_TIMELINE_ENTRY_STATE_PROGRESS = 1
# WS_MESSAGE_NOTIFICATION_TIMELINE_ENTRY_STATE_MATCHING = 2
# WS_MESSAGE_NOTIFICATION_TIMELINE_ENTRY_STATE_DOWNLOADING = 3
# WS_MESSAGE_NOTIFICATION_TIMELINE_ENTRY_STATE_LOADING = 4
WS_MESSAGE_NOTIFICATION_TIMELINE_ENTRY_STATE_FINISHED = 5
# WS_MESSAGE_NOTIFICATION_TIMELINE_ENTRY_STATE_ANALYZING = 6
WS_MESSAGE_NOTIFICATION_TIMELINE_ENTRY_STATE_DELETED = 9

WS_MESSAGE_NOTIFICATION_PLAY_SESSION_STATE = 'PlaySessionStateNotification'
WS_MESSAGE_NOTIFICATION_PLAY_SESSION_STATE_RATING_KEY = 'ratingKey'
WS_MESSAGE_NOTIFICATION_PLAY_SESSION_STATE_KEY = 'key'
WS_MESSAGE_NOTIFICATION_PLAY_SESSION_STATE_STATE = 'state'
WS_MESSAGE_NOTIFICATION_PLAY_SESSION_STATE_VIEW_OFFSET = 'viewOffset'

WS_MESSAGE_NOTIFICATION_ACTIVITY = 'ActivityNotification'
WS_MESSAGE_NOTIFICATION_ACTIVITY_ACTIVITY = 'Activity'
WS_MESSAGE_NOTIFICATION_ACTIVITY_EVENT = 'event'
# WS_MESSAGE_NOTIFICATION_ACTIVITY_EVENT_STARTED = 'started'
# WS_MESSAGE_NOTIFICATION_ACTIVITY_EVENT_UPDATED = 'updated'
WS_MESSAGE_NOTIFICATION_ACTIVITY_EVENT_ENDED = 'ended'
WS_MESSAGE_NOTIFICATION_ACTIVITY_ACTIVITY_TYPE = 'type'
WS_MESSAGE_NOTIFICATION_ACTIVITY_ACTIVITY_TYPE_REFRESH_ITEMS = 'library.refresh.items'
WS_MESSAGE_NOTIFICATION_ACTIVITY_ACTIVITY_CONTEXT = 'Context'
WS_MESSAGE_NOTIFICATION_ACTIVITY_ACTIVITY_CONTEXT_KEY = 'key'

# WS_MESSAGE_NOTIFICATION_BACKGROUND_PROCESSING_QUEUE = 'BackgroundProcessingQueueEventNotification'
# WS_MESSAGE_NOTIFICATION_STATUS = 'StatusNotification'
# WS_MESSAGE_NOTIFICATION_PROGRESS = 'ProgressNotification'
# WS_MESSAGE_NOTIFICATION_TRANSCODE_SESSION = 'TranscodeSession'
# WS_MESSAGE_NOTIFICATION_AUTO_UPDATE = 'AutoUpdateNotification'
# WS_MESSAGE_NOTIFICATION_ACCOUNT_UPDATE = 'AccountUpdateNotification'

# media provider setting identifiers and values
SETTINGS_PROVIDER_AUTHENTICATION = 'plex.authentication'
SETTINGS_PROVIDER_AUTHENTICATION_OPTION_LOCAL = 0
SETTINGS_PROVIDER_AUTHENTICATION_OPTION_MYPLEX = 1
SETTINGS_PROVIDER_LINK_MYPLEX_ACCOUNT = 'plex.linkmyplexaccount'
SETTINGS_PROVIDER_USERNAME = 'plex.username'
SETTINGS_PROVIDER_TOKEN = 'plex.token'
SETTINGS_PROVIDER_TEST_CONNECTION = 'plex.testconnection'
SETTINGS_PROVIDER_PLAYBACK_ENABLE_EXTERNAL_SUBTITLES = 'plex.enableexternalsubtitles'

# media import setting identifiers and values
SETTINGS_IMPORT_LIBRARY_SECTIONS = 'plex.librarysections'
SETTINGS_IMPORT_SYNC_SETTINGS_HASH = 'plex.syncsettingshash'
SETTINGS_IMPORT_FORCE_SYNC = 'plex.forcesync'

# player states below
PLEX_PLAYER_PLAYING = 'playing'
PLEX_PLAYER_PAUSED = 'paused'
PLEX_PLAYER_STOPPED = 'stopped'
